%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Administrator\Documents\MATLAB\GBPUSD_H4_2014.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/01/22 16:36:53

function [YMD, HHMM, O, H, L, C, V] = read_csv(filename)

%% Initialize variables.
%filename = 'C:\Users\Administrator\Documents\MATLAB\GBPUSD_H4_2014.csv';
delimiter = ',';

%% Format string for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
YMD = dataArray{:, 1};
HHMM = dataArray{:, 2};
O = dataArray{:, 3};
H = dataArray{:, 4};
L = dataArray{:, 5};
C = dataArray{:, 6};
V = dataArray{:, 7};

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

